import = ["/home/jd/.config/alacritty/themes/themes/omni.toml"]

[cursor]
blink_interval = 500

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 4
y = 4
